// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd4oz8rornvEni1nnoJDlc6I-3mr_pv5Y',
    appId: '1:110986020737:web:86c1fd04d1483b2a440a80',
    messagingSenderId: '110986020737',
    projectId: 'newsapp-bda08',
    authDomain: 'newsapp-bda08.firebaseapp.com',
    storageBucket: 'newsapp-bda08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JrYOwUZKdBYTuFCbuly6a8QU8YJOIxE',
    appId: '1:110986020737:android:f875bb0ff832c907440a80',
    messagingSenderId: '110986020737',
    projectId: 'newsapp-bda08',
    storageBucket: 'newsapp-bda08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWi6pRPz_8jWq0sBjru_pQdZtZZ86mkys',
    appId: '1:110986020737:ios:808fb7a60c1539fe440a80',
    messagingSenderId: '110986020737',
    projectId: 'newsapp-bda08',
    storageBucket: 'newsapp-bda08.firebasestorage.app',
    iosClientId: '110986020737-pp610oorq77idkgra2lgrbtnnqvlkb31.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppEyego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWi6pRPz_8jWq0sBjru_pQdZtZZ86mkys',
    appId: '1:110986020737:ios:808fb7a60c1539fe440a80',
    messagingSenderId: '110986020737',
    projectId: 'newsapp-bda08',
    storageBucket: 'newsapp-bda08.firebasestorage.app',
    iosClientId: '110986020737-pp610oorq77idkgra2lgrbtnnqvlkb31.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsAppEyego',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd4oz8rornvEni1nnoJDlc6I-3mr_pv5Y',
    appId: '1:110986020737:web:6a685ddb0d207181440a80',
    messagingSenderId: '110986020737',
    projectId: 'newsapp-bda08',
    authDomain: 'newsapp-bda08.firebaseapp.com',
    storageBucket: 'newsapp-bda08.firebasestorage.app',
  );
}
